steps:
- name: "gcr.io/cloud-builders/git"
  args:
  - "clone"
  - "https://github.com/nroduit/Weasis.git"
  - "weasis"
- name: "gcr.io/cloud-builders/git"
  args:
  - "checkout"
  - "tags/v3.6.0"
  dir: "weasis"
- name: "maven:3.6.3-jdk-14"
  volumes:
  - name: "mavenLocal"
    path: "/root/.m2"
  args:
  - "mvn"
  - "install"
  dir: "weasis"
- name: "maven:3.6.3-jdk-14"
  volumes:
  - name: "mavenLocal"
    path: "/root/.m2"
  args:
  - "mvn"
  - "install"
